services:
  - type: web
    name: recipe-django-app
    env: python
    pythonVersion: "3.12"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn recipe_project.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: SECRET_KEY
        generateValue: true
    staticPublishPath: "staticfiles"
    region: ohio
    plan: free
